# composer require symfony/apache-pack : esto espara que ande las rutas 

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#rutas
tasks:
    path: /tasks
    controller: App\Controller\TaskController::index
